dist: xenial
sudo: required
language: python

cache:
  - apt
  - pip

notifications:
  email:
    on_failure: never

before_install:
  - sudo apt-get update

install:
  - cat install.txt | xargs sudo apt-get install -y
  - pip install -r requirements.txt
  - pip install statick

script:
  - statick . --user-paths statick_config
