---
levels:
  local:
    discovery:
      - python
    tool:
      pycodestyle:
        # Make line length consistent with default for black.
        flags: "--max-line-length=88"
      pydocstyle:
        flags: ""
      pyflakes:
        flags: ""
      pylint:
        flags: "--disable=bad-continuation"
