---
name: Unit Tests

on: [pull_request, push]  # NOLINT

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v1
        if: startsWith(runner.os, 'Linux')
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade statick
          python -m pip install --upgrade -r requirements.txt

      - name: Install tools (Linux)
        run: |
          sudo apt update
          sudo apt install ffmpeg
          sudo apt install mp3wrap

      - name: Statick
        run: |
          statick . --user-paths statick_config
